server:
  port: 8080

spring:
  application:
    name: mianshi

  datasource:
    url: jdbc:mysql://192.168.0.222:3306/mianshi?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis配置
  data:
    redis:
      host: 192.168.0.222
      port: 6379
      password:  # 如果有密码就填写
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  rabbitmq:
    host: 192.168.0.222          # 或 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.czy.entity

logging:
  level:
    com.czy.mianshi.mapper: debug   # 打印SQL，便于调试
  pattern:
    console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n'